module.exports = {
  mode: 'jit',
  purge: {
    content: [
      'index.php',
      './app/**/*.php',
      './resources/**/*.{php,vue,js}',
      './resources/styles/safelist.txt',
    ],
    safelist: [
      'btn-toolbar',
      'text-grey-light',
      'nav-primary',
      'nav-backdrop',
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      'primary': '#0076FF',
      'primary-light': '#1C93FF',
      'primary-dark': '#0076D0',

      'transparent': 'transparent',

      'black': '#343940',
      'grey-darkest': '#455060',
      'grey-darker': '#66707C',
      'grey-dark': '#929BA8',
      'grey': '#b8c2cc',
      'grey-light': '#D7DDE2',
      'grey-lighter': '#E4E7EB',
      'grey-lightest': '#F7F7FA',
      'white': '#ffffff',

      'red-darkest': '#3b0d0c',
      'red-darker': '#621b18',
      'red-dark': '#cc1f1a',
      'red': '#e3342f',
      'red-light': '#ef5753',
      'red-lighter': '#f9acaa',
      'red-lightest': '#fcebea',

      'orange-darkest': '#652B0A',
      'orange-darker': '#A35022',
      'orange-dark': '#D54D00',
      'orange': '#FF5C00',
      'orange-light': '#FF8B4A',
      'orange-lighter': '#FFBE9A',
      'orange-lightest': '#FFEEE5',

      'yellow-darkest': '#453411',
      'yellow-darker': '#684f1d',
      'yellow-dark': '#f2d024',
      'yellow': '#ffed4a',
      'yellow-light': '#fff382',
      'yellow-lighter': '#fff9c2',
      'yellow-lightest': '#fcfbeb',

      'green-darkest': '#0f2f21',
      'green-darker': '#1a4731',
      'green-dark': '#1f9d55',
      'green': '#38c172',
      'green-light': '#51d88a',
      'green-lighter': '#a2f5bf',
      'green-lightest': '#e3fcec',

      'teal-darkest': '#0d3331',
      'teal-darker': '#20504f',
      'teal-dark': '#38a89d',
      'teal': '#4dc0b5',
      'teal-light': '#64d5ca',
      'teal-lighter': '#a0f0ed',
      'teal-lightest': '#e8fffe',

      'blue-darkest': '#002D60',
      'blue-darker': '#004493',
      'blue-dark': '#0062D3',
      'blue': '#0076FF',
      'blue-light': '#57A5FF',
      'blue-lighter': '#B4D7FF',
      'blue-lightest': '#E8F3FF',

      'indigo-darkest': '#191e38',
      'indigo-darker': '#2f365f',
      'indigo-dark': '#5661b3',
      'indigo': '#6574cd',
      'indigo-light': '#7886d7',
      'indigo-lighter': '#b2b7ff',
      'indigo-lightest': '#e6e8ff',

      'purple-darkest': '#21183c',
      'purple-darker': '#382b5f',
      'purple-dark': '#794acf',
      'purple': '#9561e2',
      'purple-light': '#a779e9',
      'purple-lighter': '#d6bbfc',
      'purple-lightest': '#f3ebff',

      'pink-darkest': '#451225',
      'pink-darker': '#6f213f',
      'pink-dark': '#eb5286',
      'pink': '#f66d9b',
      'pink-light': '#fa7ea8',
      'pink-lighter': '#ffbbca',
      'pink-lightest': '#ffebef',
    },
    fontFamily: {
      'sans': [
        'Roboto',
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        'Segoe UI',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ],
      'serif': [
        'Oswald',
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        'Roboto',
        'Segoe UI',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ]
    },
    spacing: {
      'px':   '1px',
      '0':    '0',
      '0-25': '.25rem',
      '0-5':  '.5rem',
      '0-75': '.75rem',
      '0':    '0',
      '1':    '1rem',
      '1-25': '1.25rem',
      '1-5':  '1.5rem',
      '1-75': '1.75rem',
      '2':    '2rem',
      '3':    '3rem',
      '4':    '4rem',
      '5':    '5rem',
      '6':    '6rem',
      '8':    '8rem',
      '10':   '10rem',
      '12':   '12rem',
      '16':   '16rem',
      '20':   '20rem',
      '24':   '24rem',
      '32':   '32rem',
    },
    extend: {
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
};
